services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE team;' -U postgres
notifications: 
  email: false
sudo: false 

language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
before_script:
  - npm install
scripts:
  - npm run test
after_success:
  - npm run coveralls







